apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-transit-unseal-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-transit-unseal-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vault-transit-unseal-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "vault-transit-unseal-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vault-transit-unseal-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        securityContext:
          {{- toYaml .Values.controllerManager.securityContext | nindent 10 }}
        image: {{ include "vault-transit-unseal-operator.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{- with .Values.controllerManager.manager.args }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.watchNamespace }}
        - --namespace={{ .Values.watchNamespace }}
        {{- end }}
        {{- if .Values.skipCrdInstall }}
        - --skip-crd-install
        {{- end }}
        {{- if .Values.enableLeaderElection }}
        - --leader-elect
        {{- end }}
        {{- if ne (int .Values.maxConcurrentReconciles) 3 }}
        - --max-concurrent-reconciles={{ .Values.maxConcurrentReconciles }}
        {{- end }}
        {{- if ne .Values.reconcileTimeout "5m" }}
        - --reconcile-timeout={{ .Values.reconcileTimeout }}
        {{- end }}
        {{- if ne .Values.vaultTimeout "30s" }}
        - --vault-timeout={{ .Values.vaultTimeout }}
        {{- end }}
        {{- if not .Values.vaultTlsValidation }}
        - --vault-tls-validation=false
        {{- end }}
        env:
        {{- with .Values.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.controllerManager.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.controllerManager.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.controllerManager.resources | nindent 10 }}
        {{- with .Values.extraVolumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.kubeRbacProxy.enabled }}
      - name: kube-rbac-proxy
        securityContext:
          {{- toYaml .Values.kubeRbacProxy.securityContext | nindent 10 }}
        image: {{ include "vault-transit-unseal-operator.kubeRbacProxyImage" . }}
        args:
          {{- toYaml .Values.kubeRbacProxy.args | nindent 8 }}
        ports:
        - containerPort: 8443
          protocol: TCP
          name: https
        resources:
          {{- toYaml .Values.kubeRbacProxy.resources | nindent 10 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
      {{- toYaml . | nindent 6 }}
      {{- end }}