{{- if .Values.createNamespace -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "vault-transit-unseal-operator.labels" . | nindent 4 }}
{{- end }}