{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vault-transit-unseal-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-transit-unseal-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vault-transit-unseal-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8443  # Metrics
    - protocol: TCP
      port: 8081  # Health
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443   # Kubernetes API
    - protocol: TCP
      port: 8200  # Vault
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: vault
    ports:
    - protocol: TCP
      port: 8200
  # Allow DNS
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
{{- end }}