# Test with environment configuration
env:
  DOMAIN: example.com
  ENVIRONMENT: production

envFrom:
- configMapRef:
    name: test-config
- secretRef:
    name: test-secret

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi