# Security-focused configuration test
# This tests the chart with all security features enabled

# Enable all security features
networkPolicy:
  enabled: true

# Strict pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

# Even stricter container security context
controllerManager:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    seccompProfile:
      type: RuntimeDefault

# Custom annotations for security scanning
podAnnotations:
  container.apparmor.security.beta.kubernetes.io/manager: runtime/default
  container.seccomp.security.alpha.kubernetes.io/manager: runtime/default

# Limit resources to prevent DoS
controllerManager:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
      ephemeral-storage: 100Mi
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 50Mi

# Enable service monitor with TLS
serviceMonitor:
  enabled: true
  labels:
    prometheus: kube-prometheus
  interval: 30s
  scrapeTimeout: 10s