apiVersion: v2
name: builder-webapp
description: website-builder SPA + auth backend (openauth client + session cookie)
type: application
version: 0.0.28
appVersion: 0.0.28
maintainers:
  - name: frederic.rous
icon: https://github.githubassets.com/images/icons/emoji/sparkles.png
